### ISSUE TITLE
the app crashes after the Log-in

### ISSUE THREAD

**Issue by arturfenko** [echoes221/cryptotrackr#1]
![image](https://user-images.githubusercontent.com/7466397/29217965-f62f816c-7ebb-11e7-98ed-b74b9e1ae994.png)

**Comment by arturfenko** [comment]
![image](https://user-images.githubusercontent.com/7466397/29218021-243e688e-7ebc-11e7-8bce-ea5f3cc9ca2d.png)

**Comment by calumpeak** [comment]
Wrong repo my friend
